services:
  db:
    image: postgres:15-alpine
    container_name: cocktail_db
    environment:
      POSTGRES_DB: cocktails
      POSTGRES_USER: cocktails
      POSTGRES_PASSWORD: cocktails
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: cocktail_api
    depends_on:
      - db
    ports:
      - "3333:3333"
    env_file:
      - .env
    restart: always

volumes:
  db-data:
