name: CI and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # Usuń lub zakomentuj poniższą linię, jeśli nie masz zadania "generate"
    # needs: generate
    steps:
      - name: Deploy to Raspberry Pi via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.RPI_HOST }}       # IP lub DNS Twojego Raspberry Pi
          username: ${{ secrets.RPI_USER }}     # Zwykle "pi" lub inny użytkownik
          password: ${{ secrets.RPI_SECRET }}        # Prywatny klucz SSH przechowywany w secrets
          # Jeśli SSH działa na niestandardowym porcie, możesz dodać:
          # port: ${{ secrets.RPI_PORT }}
          script: |
            cd /home/fox/256gb_drive/server/apps/backend-cocktail-api
            git pull origin main
            docker-compose down
            docker-compose up -d --build

